baseurl = "https://maintainerati.org/"
languageCode = "en-us"
title = "Maintainerati"

[params]
  description = "An unconference, open space for open source software maintainers."
  slack = "https://maintainerati.slack.com"
  slackInvite = "/slack-invite"
  author = "The Maintainerati"
  date = "19 November, 2017"
  [params.location]
    name = "Xebia"
    city = "Amsterdam"
    url = "https://xebia.com/"
